name: Deploy Frontend
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and test
        run: |
          docker build -t cygnetops/react-test -f Dockerfile.dev .
          docker run -e CI=true cygnetops/react-test npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v15
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          region: us-east-1
          application_name: daktcg
          environment_name: daktcg-env
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
